"""The AWS-hosted counterpart to vfr_pipeline_dag.py: same five stages
(Collect -> Feature-Engineer -> Retrain -> Evaluate -> Promote), but Collect/
Feature-Engineer/Retrain run as real SageMaker Processing/Training Jobs
instead of DockerOperator sibling containers -- there's no host Docker
socket to launch siblings from once Airflow itself runs on Fargate (see
docker/Dockerfile.airflow.aws). Evaluate/Promote stay in-process, same as
the local DAG, for the same reason: vfr.model_registry has zero third-party
dependencies, so there's no compute to hand off either way.

Only this DAG file (not vfr_pipeline_dag.py) ships in the AWS Airflow image
-- docker/Dockerfile.airflow.aws copies just this one in, since
vfr_pipeline_dag.py's DockerOperator tasks reference a host Docker socket
that doesn't exist on Fargate and would fail to parse there.

Configuration comes from Airflow Variables, set once after the Airflow
Fargate service is up (`airflow variables set <key> <value>`, or via the
UI) -- these are per-environment values a DAG file shouldn't hardcode:

- vfr_data_s3_bucket        -- matches the DataS3BucketName CloudFormation
                                parameter; candidates/features/labels/model
                                artifacts all live under this bucket.
- vfr_sagemaker_job_role_arn -- matches SageMakerJobRole's ARN (a stack
                                 output; see infra/cloudformation/template.yaml).
- vfr_pipeline_processing_image_uri / vfr_pipeline_training_image_uri
                                -- the ECR URIs CI pushed
                                   pipeline-processing/pipeline-training to.
- vfr_sagemaker_instance_type -- defaults to ml.m5.large if unset.

Labels (data/labels/spottability_ratings.csv) are hand-produced, not
generated by any pipeline stage -- upload the current file to
s3://<vfr_data_s3_bucket>/labels/spottability_ratings.csv yourself before
triggering this DAG; Feature-Engineer's own output lands under
s3://<vfr_data_s3_bucket>/features/ automatically.
"""
from __future__ import annotations

from airflow.providers.amazon.aws.operators.sagemaker import (
    SageMakerProcessingOperator,
    SageMakerTrainingOperator,
)
from airflow.providers.standard.operators.python import ShortCircuitOperator
from airflow.sdk import Variable, dag, task
from pendulum import datetime


def _s3_bucket() -> str:
    return Variable.get("vfr_data_s3_bucket")


def _job_role_arn() -> str:
    return Variable.get("vfr_sagemaker_job_role_arn")


def _instance_type() -> str:
    return Variable.get("vfr_sagemaker_instance_type", default_var="ml.m5.large")


def _processing_config(job_name: str, image_uri_var: str, container_arguments: list[str],
        input_s3_uri: str | None, output_s3_uri: str) -> dict:
    processing_inputs = []
    if input_s3_uri:
        processing_inputs.append({
            "InputName": "input",
            "S3Input": {
                "S3Uri": input_s3_uri,
                "LocalPath": "/opt/ml/processing/input",
                "S3DataType": "S3Prefix",
                "S3InputMode": "File",
            },
        })
    return {
        "ProcessingJobName": job_name,
        "RoleArn": _job_role_arn(),
        "AppSpecification": {
            "ImageUri": Variable.get(image_uri_var),
            "ContainerEntrypoint": ["python3", "-m", "vfr.pipeline"],
            "ContainerArguments": container_arguments,
        },
        "ProcessingInputs": processing_inputs,
        "ProcessingOutputConfig": {
            "Outputs": [{
                "OutputName": "output",
                "S3Output": {
                    "S3Uri": output_s3_uri,
                    "LocalPath": "/opt/ml/processing/output",
                    "S3UploadMode": "EndOfJob",
                },
            }],
        },
        "ProcessingResources": {
            "ClusterConfig": {
                "InstanceCount": 1,
                "InstanceType": _instance_type(),
                "VolumeSizeInGB": 20,
            },
        },
        "StoppingCondition": {"MaxRuntimeInSeconds": 3600},
    }


@dag(
    dag_id="vfr_pipeline_aws",
    description="AWS-hosted Collect -> Feature-Engineer -> Retrain -> Evaluate -> Promote, via SageMaker Jobs",
    schedule=None,
    start_date=datetime(2026, 9, 9, tz="UTC"),
    catchup=False,
    # One run at a time. Every stage hands off through one fixed place --
    # the candidate model evaluate reads is the one promote copies later --
    # so a second run's retrain between the two would put a model into
    # service that never passed the gate. A second trigger queues.
    max_active_runs=1,
    tags=["vfr", "ml", "aws"],
)
def vfr_pipeline_aws():
    bucket = _s3_bucket()
    run_id = "{{ run_id }}"

    collect = SageMakerProcessingOperator(
        task_id="collect",
        config=_processing_config(
            job_name=f"vfr-collect-{run_id}",
            image_uri_var="vfr_pipeline_processing_image_uri",
            container_arguments=["collect", "--out-path", "/opt/ml/processing/output/candidates.csv"],
            input_s3_uri=None,
            output_s3_uri=f"s3://{bucket}/candidates/",
        ),
    )

    feature_engineer = SageMakerProcessingOperator(
        task_id="feature_engineer",
        config=_processing_config(
            job_name=f"vfr-feature-engineer-{run_id}",
            image_uri_var="vfr_pipeline_processing_image_uri",
            container_arguments=[
                "engineer-features",
                "--in-path", "/opt/ml/processing/input/candidates.csv",
                "--out-path", "/opt/ml/processing/output/features.parquet",
            ],
            input_s3_uri=f"s3://{bucket}/candidates/",
            output_s3_uri=f"s3://{bucket}/features/",
        ),
    )

    retrain = SageMakerTrainingOperator(
        task_id="retrain",
        config={
            "TrainingJobName": f"vfr-retrain-{run_id}",
            "RoleArn": _job_role_arn(),
            "AlgorithmSpecification": {
                "TrainingImage": Variable.get("vfr_pipeline_training_image_uri"),
                "TrainingInputMode": "File",
            },
            # No ContainerArguments override exists for Training Jobs --
            # Dockerfile.training's own `CMD ["retrain"]` default is what
            # actually runs; retrain() itself picks up SM_CHANNEL_FEATURES/
            # SM_CHANNEL_LABELS/SM_MODEL_DIR (see _retrain_defaults() in
            # src/vfr/pipeline.py) from the channels/output path below.
            "InputDataConfig": [
                {
                    "ChannelName": "features",
                    "DataSource": {"S3DataSource": {
                        "S3DataType": "S3Prefix",
                        "S3Uri": f"s3://{bucket}/features/",
                        "S3DataDistributionType": "FullyReplicated",
                    }},
                },
                {
                    "ChannelName": "labels",
                    "DataSource": {"S3DataSource": {
                        "S3DataType": "S3Prefix",
                        "S3Uri": f"s3://{bucket}/labels/",
                        "S3DataDistributionType": "FullyReplicated",
                    }},
                },
            ],
            "OutputDataConfig": {"S3OutputPath": f"s3://{bucket}/models/"},
            "ResourceConfig": {
                "InstanceCount": 1,
                "InstanceType": _instance_type(),
                "VolumeSizeInGB": 20,
            },
            "StoppingCondition": {"MaxRuntimeInSeconds": 3600},
        },
    )

    def _metrics_pass() -> bool:
        from vfr import model_registry

        return model_registry.evaluate()

    evaluate = ShortCircuitOperator(task_id="evaluate", python_callable=_metrics_pass)

    @task
    def promote() -> str:
        from vfr import model_registry

        return str(model_registry.promote())

    collect >> feature_engineer >> retrain >> evaluate >> promote()


vfr_pipeline_aws()
